### ISSUE TITLE
invalid INFO tag for 1000G

### ISSUE THREAD

**Issue by edg1983** [fakedrtom/SVAFotate#13]
Hello!

This is an excellent tool for annotating SV AFs! Thanks!

I've noticed that when annotating from the 1000G sources, SVAFotate adds INFO tags like `1000G_Count` and `1000G_SV_Cov`. 

However, these are not valid INFO tags in BCF format since a valid tag ID for an INFO field can not start with a number. This creates issues downstream when one wants to process the annotated file using bcftools (or other tools based on the htslib).

I suggest changing the ID of any newly inserted tag to ensure they always start with a character.

**Comment by fakedrtom** [comment]
Thanks! I am glad you like the tool!

Yes, I regret my naming choice as I have been aware of the invalid tag problem for a little while. I will update this. Thank you!

**Comment by fakedrtom** [comment]
I have updated this in a new core file for SVAFotate that includes gnomADv4.1 which you can download [here](https://zenodo.org/records/11642574). Hopefully this makes the output more usable with downstream processing.
