### ISSUE TITLE
Feature request: gnomAD v4.0 SV

### ISSUE THREAD

**Issue by jsquaredosquared** [fakedrtom/SVAFotate#19]
Thanks for this tool.

I would like to use the [gnomAD v4.0 SV dataset](https://gnomad.broadinstitute.org/news/2023-11-v4-structural-variants/) to annotate a SV VCF, but I am not sure how to create the BED file myself.

Do you have any plans to update the default BED file to include gnomAD v4.0 SV? Or is it possible to provide it as a separate BED file?

**Comment by fakedrtom** [comment]
Glad you like the tool! I am planning on adding gnomAD v4.0 to the provided BED. Nearly have it finished, but I am delayed by other pressing matters. Hope to have this uploaded soon!
