### ISSUE TITLE
installation issue using pip

### ISSUE THREAD

**Issue by prasundutta87** [fakedrtom/SVAFotate#21]
Hi,

I tried installing SVAFotate in a new conda enviroment today and I got this error- 

`pip install git+https://github.com/fakedrtom/SVAFotate.git
Collecting git+https://github.com/fakedrtom/SVAFotate.git
  Cloning https://github.com/fakedrtom/SVAFotate.git to /tmp/pip-req-build-9akg5rr3
  Running command git clone --quiet https://github.com/fakedrtom/SVAFotate.git /tmp/pip-req-build-9akg5rr3
  Downloading supporting_data/gnomad.v4.bed.gz (356 MB)
  Error downloading object: supporting_data/gnomad.v4.bed.gz (b7ea0af): Smudge error: Error downloading supporting_data/gnomad.v4.bed.gz (b7ea0af44cfad1061397aadf2425d355c8a4b0052b51aeb23c9f5905fd15bf1f): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

  Errors logged to /tmp/pip-req-build-9akg5rr3/.git/lfs/logs/20240129T171426.634724821.log
  Use `git lfs logs last` to view the log.
  error: external filter git-lfs smudge -- %f failed 2
  error: external filter git-lfs smudge -- %f failed
  fatal: supporting_data/gnomad.v4.bed.gz: smudge filter lfs failed
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry the checkout with 'git checkout -f HEAD'

  error: subprocess-exited-with-error

  × git clone --quiet https://github.com/fakedrtom/SVAFotate.git /tmp/pip-req-build-9akg5rr3 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet https://github.com/fakedrtom/SVAFotate.git /tmp/pip-req-build-9akg5rr3 did not run successfully.
│ exit code: 128
╰─> See above for output.`

Is some update going on, in the lines of gnomad.v4 as seen above in the error message?

Regards,
Prasun

**Comment by fakedrtom** [comment]
Yes, there is a problem with the gnomad.v4.bed.gz file and it is no longer usable for the time being. I believe this is the reason for the problem. I have removed gnomad.v4.bed.gz from the repo for the time being. Would you mind trying again and seeing if the installation works now?

**Comment by prasundutta87** [comment]
HI @fakedrtom..thanks for the quick reply. Yes, it worked now! Thanks a lot!

**Comment by fakedrtom** [comment]
Great! I'll hopefully have the new gnomAD back and in a more usable form soon.
