### ISSUE TITLE
1000 Genomes Allele Frequencies

### ISSUE THREAD

**Issue by cathaloruaidh** [fakedrtom/SVAFotate#4]
Hi,

Really useful tool! I have a query about the allele frequency annotation from 1000G. I annotated a deletion spanning the following region on GRCh38:

`chr7   101357967    101360519`

I used a 50% reciprocal overlap with the 1000G only from the supporting data, and the Max_AF was 0.609443. However, I tried to re-create the allele frequency BED file, and following the same annotation criteria with the custom data the Max_AF comes out to be 0.0217652. I used the data from the 1000 Genomes Phase 3 SV callset (https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/integrated_sv_map/) to generate my custom BED file (converted to GRCh38 with liftOver). The above deletion has a 50% reciprocal overlap with "HGSV_146974" in your supporting BED file and with "BI_GS_DEL1_B4_P1340_1" in the 1000 Genomes VCF file. 

I was wondering where you derived the allele frequencies for the 1000G calls? 

All the best,
Cathal

**Comment by fakedrtom** [comment]
I apologize that I did not see this question earlier! For 1000G AFs I used the following:

https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20210124.SV_Illumina_Integration/1KGP_3202.Illumina_ensemble_callset.freeze_V1.vcf.gz

In this case I did not derive the AFs at all, but used what was reported in the VCF. Looks to me like the call set you used is about 4 years older.

**Comment by cathaloruaidh** [comment]
Ah, that makes sense, the issue is between the Phase 3 and the new high-coverage releases of the 1000G. Thanks for clarifying!
